[package]
name = "grep_lite"
version = "0.1.0"
edition = "2021"
authors = ["Adrian Aarland"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
regex = "1"
